### ISSUE TITLE
Add support for iAMT

### ISSUE THREAD

**Issue by rgl** [bmc-toolbox/bmclib#131]
Is it feasible to add support for [iAMT](https://en.wikipedia.org/wiki/Intel_Active_Management_Technology) (used to manage kiosk like devices)? Or is that out-of-scope?

There is at least the the [MeshCentral application/library](https://github.com/Ylianst/MeshCentral) (written in node.js) that seems to have good support for it.

**Comment by joelrebel** [comment]
@rgl at the moment, iAMT support would be out of scope, although it is an interesting suggestion,
if I end up having to deal with such devices - I'll consider adding in support.

**Comment by jacobweinstock** [comment]
AMT support would enable interacting with machines like intel NUCs. There has been request for that in some of the consumer programs of bmclib. For example here, https://github.com/tinkerbell/pbnj/issues/134

There is an existing Go library that I've been playing with that could get us some basic functionality like power and next boot support. It is functioning properly with the NUC i have in my home lab. http://github.com/ammmze/go-amt
