### ISSUE TITLE
difference in supermicro X11s

### ISSUE THREAD

**Issue by jacobweinstock** [bmc-toolbox/bmclib#183]
got some feedback that the current support for SuperMicro X11 doesn't work for all models of X11. The existing X11 support was written and tested with X11SCM-F in mind. It was reported that X11DSC+ appears to not work, but might work if it was using the X10 code. 

I think we need to re-evaluate how we probe for compatibility between SuperMicro models. 

Currently, after determining that the BMC is a SuperMicro we call `conn.HardwareType()` [here](https://github.com/bmc-toolbox/bmclib/blob/85f37d5bb6e98e478c9a31e1a2174ee420ca3259/discover/probe.go#L262) and [here](https://github.com/bmc-toolbox/bmclib/blob/85f37d5bb6e98e478c9a31e1a2174ee420ca3259/discover/probe.go#L294) and compare it to a constant of the BMC model number. either `x11` or `x10`. Whichever one it matches we use. This leaves 
X11DSC+ not functioning, as reported.

One option could be to not only check this value but if the `conn.HardwareType()` (or another command) actually worked. and then use that provider implementation.

Any other thoughts or ideas?

**Comment by joelrebel** [comment]
@jacobweinstock, are the X11DSC+ not identified at all or what (if any) errors are seen, or which bmclib methods fail to work?

one option here would be to define another 'generic' supermicro [probe identifier](https://github.com/bmc-toolbox/bmclib/blob/85f37d5bb6e98e478c9a31e1a2174ee420ca3259/discover/discover.go#L15) in which the device board name/model number is identified using `ipmitool -I lanplus -H <IP> -U ADMIN -P <password> fru`

another option would be to define a X11DSC+ [probe identifier](https://github.com/bmc-toolbox/bmclib/blob/85f37d5bb6e98e478c9a31e1a2174ee420ca3259/discover/discover.go#L15) with the caller passing in the [probe hint](https://github.com/bmc-toolbox/bmclib/blob/85f37d5bb6e98e478c9a31e1a2174ee420ca3259/discover/discover.go#L111)
