### ISSUE TITLE
Deleted tags - Cut a v0.5.3 release

### ISSUE THREAD

**Issue by micahhausler** [bmc-toolbox/bmclib#262]
There is a mismatch and some apparently deleted git tags between GitHub and Go's module package cache

The latest GitHub release shows up as [v0.4.15](https://github.com/bmc-toolbox/bmclib/releases/tag/v0.4.15), while Go's package cache shows [v0.5.2](https://pkg.go.dev/github.com/bmc-toolbox/bmclib@v0.5.2?tab=versions).

In order for importers to use the correct latest, can we cut a tag for v0.5.3?

**Comment by jacobweinstock** [comment]
This seems reasonable to me. @joelrebel do you want to get https://github.com/bmc-toolbox/bmclib/pull/261 and then we cut a tag/release?

**Comment by joelrebel** [comment]
Yep!

**Comment by joelrebel** [comment]
with this included, we're ready for a release https://github.com/bmc-toolbox/bmclib/pull/272
