### ISSUE TITLE
Rename v2 branch to main and master branch as v1

### ISSUE THREAD

**Issue by joelrebel** [bmc-toolbox/bmclib#294]
There have been suggestions to rename the bmclib [v2 branch](https://github.com/bmc-toolbox/bmclib/tree/v2) to `main` which will be 'mainline'. And further development continues with bmclib v2 as the `main` branch. 

To have this done, we're taking the following steps
- current `master` HEAD will be tagged with `v1.0.0` (to be called bmclib legacy going ahead).
- rename current `master` branch to `v1`.
- rename `v2` branch as `main`.

For consumers, contributors to the legacy `v1` branch:

- Applications importing the legacy bmclib can continue as is.
- The import path is `github.com/bmc-toolbox/bmclib`
- Going ahead, any fixes/features to the legacy `v1.0.0` codebase will require a PR based on the `v1` branch.

For consumers, contributors of bmclib `v2`.
- The import path is `github.com/bmc-toolbox/bmclib/v2`
- PRs are to be made on the `main` branch.

@jibsonline @nnuss @omar-m-othman @jacobweinstock @chrisdoherty4 if you can leave an ack in the comments, I'll then proceed with this change.

**Comment by nnuss** [comment]
Ack. I agree it's time to both fixup the master/main naming and make v2 the mainline branch.

**Comment by chrisdoherty4** [comment]
That works.

lgtm

**Comment by jacobweinstock** [comment]
Sounds good. Thanks @joelrebel

**Comment by joelrebel** [comment]
This is now done, make sure your local `v2` branch is renamed to `main` and tracks the current `main`.
